# Generated by Django 5.2.7 on 2025-11-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studysession_created_at_studysession_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='created_by',
        ),
    ]
